import { Inter } from "next/font/google";
import "./globals.css";
import NavbarWithMegaMenu from "@/components/NavbarComponent";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavbarWithMegaMenu />
				<main className="bg-[#f5f5f5]">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
